package com.company.oop.taskmanagementsystem.commands.enums;

public enum CommandType {
    //TODO update command names to be the same
    // as command classes
    CREATEMEMBER,//*
    SHOWALLMEMBERS,//*
    SHOWMEMBERACTIVITY, //*

    CREATENEWTEAM, //*
    SHOWALLTEAMS,//*
    SHOWTEAMACTIVITY,
    ADDPERSONTOTEAM, //*
    SHOWALLTEAMMEMBERS,//*

    CREATENEWBOARDINTEAM, //*
    SHOWALLTEAMBOARDS, //*
    SHOWBOARDACTIVITY,//*

    CREATENEWBUG,//*
    CREATENEWSTORY,//*
    CREATEFEEDBACK,//*

    CHANGEPRIORITYOFBUG, //*
    CHANGESTATUSOFBUG, //*
    CHANGESEVERITYOFBUG, //*

    CHANGEPRIORITYOFSTORY, //*
    CHANGESIZEOFSTORY,//*
    CHANGESTATUSOFSTORY, //*

    CHANGERATINGOFFEEDBACK, //*
    CHANGESTATUSOFFEEDBACK, //*

    ASSIGNTASKTOMEMBER, //*
    UNASSIGNTASKTOMEMBER, //*

    ADDCOMMENTTOTASK, //*

    LISTALLTASKS, //*
    FILTERTASKSBYTITLE,
    SORTTASKSBYTITLE, //*

    LISTBUGS, //*
    LISTSTORIES,//*
    LISTFEEDBACK,//*
    FILTERTASKBYSTATUSORANDASSIGNEE, //*
    FILTERTASKWITHASSIGNEEBYSTATUSANDORASSIGNEE, //*

    SORTTASKSBYPRIORITY,
    SORTTASKSBYSEVERITY,
    SORTTASKSBYSIZE,
    SORTTASKSBYRATING,

    LISTTASKSWITHASSIGNEE,
    LISTTASKWITHASSIGNEESORTEDBYTITLE;


}
