package com.company.oop.taskmanagementsystem.commands.enums;

public enum CommandType {

    CREATENEWMEMBER,
    SHOWALLMEMBERS,
    SHOWMEMBERACTIVITY,

    CREATENEWTEAM,
    SHOWALLTEAMS,
    SHOWTEAMACTIVITY,
    ADDMEMBERTOTEAM,
    SHOWALLTEAMMEMBERS,

    CREATENEWBOARDINTEAM,
    SHOWALLTEAMBOARDS,
    SHOWBOARDACTIVITY,

    CREATENEWBUG,
    CREATENEWSTORY,
    CREATEFEEDBACK,

    CHANGEPRIORITYOFBUG, 
    CHANGESTATUSOFBUG, 
    CHANGESEVERITYOFBUG, 

    CHANGEPRIORITYOFSTORY, 
    CHANGESIZEOFSTORY,
    CHANGESTATUSOFSTORY, 

    CHANGERATINGOFFEEDBACK, 
    CHANGESTATUSOFFEEDBACK, 

    ASSIGNTASKTOMEMBER, 
    UNASSIGNTASKTOMEMBER, 

    ADDCOMMENTTOTASK, 

    LISTALLTASKS, 
    FILTERTASKSBYTITLE,
    SORTTASKSBYTITLE,

    LISTALLBUGS,
    LISTALLSTORIES,
    LISTALLFEEDBACK,
    FILTERTASKBYSTATUSORANDASSIGNEE,
    FILTERTASKWITHASSIGNEEBYSTATUSANDORASSIGNEE,
    SORTBUGBY,
    SORTSTORYBY,
    SORTFEEDBACKBY,
    LISTTASKSWITHASSIGNEE,
    LISTTASKWITHASSIGNEESORTEDBYTITLE;


}
